#DO NOT CHANGE THESE
name: MiniGames-Core
main: me.wundero.MiniGames_Core.Core
version: 0.0.0
#DO NOT CHANGE THESE

authors: [hellostanleylee, Wundero]
website: 

prefex: [MiniGames-Core]
softdepend: [Vault, CoreProtect, WorldEdit]
#TODO add commands, permissions and authors list
